version: "3"

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn main:app --host "0.0.0.0" --port 8000 --reload"
  redis:
    image: redis:7.0.8-alpine3.17
    ports:
      - "6379:6379"
